language: node_js
node_js:
 - "node"

cache: npm

script: npm run build && echo 'StereoViking.com' > dist/CNAME

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 target_branch: gh-pages
 keep_history: false
 on:
   branch: master